version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
      MYSQL_DATABASE: meubanco
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p", "Senha123"]
      timeout: 20s
      retries: 3

  web:
    image: nginx:latest
    ports:
      - "4500:80" # Mudamos a porta aqui para a padrão do Nginx dentro do container
    volumes:
      - ./php:/var/www/html:ro # Monta o diretório php no contêiner do Nginx (somente leitura)
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Monta a configuração do Nginx
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 3s
      retries: 3

  php:
    build: ./php
    volumes:
      - ./php:/var/www/html:rw # Monta o diretório php para o PHP-FPM
    depends_on:
      - db

volumes:
  db_data: